# Generated by Django 2.2.4 on 2019-10-09 02:04

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_date', models.DateTimeField(auto_now_add=True, verbose_name='待预测日期')),
                ('pre_type', models.CharField(max_length=20, verbose_name='类型')),
                ('isDel', models.BooleanField(default=True, verbose_name='是否删除')),
                ('pre_result', models.CharField(max_length=20, verbose_name='预测结果')),
                ('creator_id', models.IntegerField(default=1, verbose_name='创建者id')),
                ('update_id', models.IntegerField(default=1, verbose_name='更新者id')),
                ('lastTime', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '预测数据',
            },
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.CharField(max_length=20)),
                ('gdate', models.DateTimeField()),
                ('ggirlnum', models.IntegerField()),
                ('gboynum', models.IntegerField()),
                ('isDelete', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'grades',
            },
        ),
        migrations.CreateModel(
            name='Inform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inform_id', models.IntegerField(max_length=20, verbose_name='通知id')),
                ('content', models.CharField(max_length=20, verbose_name='内容')),
                ('focus_id', models.IntegerField(verbose_name='关注用户的id')),
                ('isSend', models.BooleanField(default=True, verbose_name='是否收到')),
                ('creator_id', models.IntegerField(default=1, verbose_name='创建者id')),
                ('update_id', models.IntegerField(default=1, verbose_name='更新者id')),
                ('lastTime', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('isDel', models.BooleanField(default=True, verbose_name='是否删除')),
            ],
        ),
        migrations.CreateModel(
            name='Rawdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='时间')),
                ('address', models.CharField(max_length=20, verbose_name='地址')),
                ('temperature', models.FloatField(max_length=20, verbose_name='温度')),
                ('humidity', models.FloatField(max_length=20, verbose_name='湿度')),
                ('atmospheric', models.FloatField(max_length=20, verbose_name='气压')),
                ('precipitation', models.IntegerField(verbose_name='降水')),
                ('sunshine', models.IntegerField(verbose_name='日照')),
                ('wind', models.FloatField(max_length=20, verbose_name='地址')),
                ('aqi', models.IntegerField(verbose_name='空气质量')),
                ('pm2', models.FloatField(max_length=20, verbose_name='pm2.5')),
                ('pm10', models.FloatField(max_length=20, verbose_name='pm10')),
                ('SO2', models.FloatField(max_length=20, verbose_name='SO2')),
                ('CO', models.FloatField(max_length=20, verbose_name='CO')),
                ('NO2', models.FloatField(max_length=20, verbose_name='NO2')),
                ('O3', models.FloatField(max_length=20, verbose_name='O3')),
                ('incidence', models.FloatField(max_length=20, verbose_name='发病数')),
            ],
            options={
                'verbose_name_plural': '天气、污染原始数据',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20, verbose_name='用户名')),
                ('login_id', models.IntegerField(verbose_name='登陆id')),
                ('user_password', models.CharField(default='12345678', editable=False, max_length=20, verbose_name='登陆密码')),
                ('tele', models.CharField(max_length=20, verbose_name='手机号码')),
                ('mail', models.CharField(max_length=20, verbose_name='邮箱')),
                ('isInform', models.BooleanField(default=True, verbose_name='是否通知')),
                ('isMail', models.BooleanField(default=True, verbose_name='是否发邮件')),
                ('user_type', models.IntegerField(choices=[(1, 'user'), (2, 'admin')], default=1, verbose_name='用户类型')),
                ('power_type', models.CharField(max_length=20, verbose_name='用户权限')),
                ('creator_id', models.IntegerField(verbose_name='创建者id')),
                ('update_id', models.IntegerField(verbose_name='更新者id')),
                ('lastTime', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('isDel', models.BooleanField(default=True, verbose_name='是否删除')),
                ('img', models.ImageField(blank=True, null=True, upload_to='upload', verbose_name='头像')),
            ],
            options={
                'verbose_name_plural': '用户管理',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=20)),
                ('sgender', models.BooleanField(default=True)),
                ('sage', models.IntegerField(db_column='age')),
                ('scontend', models.CharField(max_length=20)),
                ('isDelete', models.BooleanField(default=False)),
                ('lastTime', models.DateTimeField(auto_now=True)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('sgrade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Grades')),
            ],
            options={
                'db_table': 'students',
                'ordering': ['id'],
            },
            managers=[
                ('stuObj', django.db.models.manager.Manager()),
            ],
        ),
    ]
