# Generated by Django 2.2.4 on 2019-12-19 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Information_id', models.IntegerField(default=1, verbose_name='资讯id')),
                ('content', models.CharField(max_length=2000, verbose_name='资讯内容')),
                ('isShow', models.BooleanField(default=True, verbose_name='是否显示')),
                ('creator_id', models.IntegerField(default=1, verbose_name='创建者id')),
                ('update_id', models.IntegerField(default=1, verbose_name='更新者id')),
                ('lastTime', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('isDel', models.BooleanField(default=True, verbose_name='是否能删除')),
            ],
            options={
                'verbose_name_plural': '资讯管理',
            },
        ),
    ]
