# Generated by Django 2.2.6 on 2019-10-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdata',
            name='date',
            field=models.DateTimeField(verbose_name='时间'),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_password',
            field=models.CharField(default='12345678', editable=False, max_length=20, verbose_name='登陆密码'),
        ),
    ]
