# Generated by Django 2.2.4 on 2019-10-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_auto_20191009_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jurisdiction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_id', models.IntegerField(default=1, verbose_name='权限id')),
                ('root_name', models.CharField(max_length=20, verbose_name='权限名')),
                ('creator_id', models.IntegerField(default=1, verbose_name='创建者id')),
                ('update_id', models.IntegerField(default=1, verbose_name='更新者id')),
                ('lastTime', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('isDel', models.BooleanField(default=True, verbose_name='是否删除')),
            ],
            options={
                'verbose_name_plural': '权限管理',
            },
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.CharField(max_length=20, verbose_name='留言内容'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.IntegerField(default=1, verbose_name='留言id'),
        ),
    ]
