# Generated by Django 2.2.4 on 2019-10-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_auto_20191009_1714'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grades',
            options={'verbose_name_plural': '测试1'},
        ),
        migrations.AlterModelOptions(
            name='students',
            options={'verbose_name_plural': '测试2'},
        ),
        migrations.AddField(
            model_name='users',
            name='user_Token',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.CharField(max_length=2000, verbose_name='留言内容'),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='wind',
            field=models.FloatField(max_length=20, verbose_name='风力'),
        ),
        migrations.AlterModelTable(
            name='grades',
            table=None,
        ),
        migrations.AlterModelTable(
            name='students',
            table=None,
        ),
    ]
