# Generated by Django 2.2.4 on 2019-10-18 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_auto_20191017_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='img',
        ),
        migrations.AlterField(
            model_name='collect',
            name='collect_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='collect',
            name='isDel',
            field=models.BooleanField(default=True, verbose_name='是否能删除'),
        ),
        migrations.AlterField(
            model_name='inform',
            name='isDel',
            field=models.BooleanField(default=True, verbose_name='是否能删除'),
        ),
        migrations.AlterField(
            model_name='jurisdiction',
            name='isDel',
            field=models.BooleanField(default=True, verbose_name='是否能删除'),
        ),
        migrations.AlterField(
            model_name='jurisdiction',
            name='root_name',
            field=models.IntegerField(choices=[(1, '预测发病数'), (2, '爬取数据'), (3, '保存数据')], default=1, verbose_name='权限名'),
        ),
        migrations.AlterField(
            model_name='message',
            name='isDel',
            field=models.BooleanField(default=True, verbose_name='是否能删除'),
        ),
        migrations.AlterField(
            model_name='users',
            name='isDel',
            field=models.BooleanField(default=True, verbose_name='是否能删除'),
        ),
    ]
