# Generated by Django 2.2.4 on 2019-10-18 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_auto_20191018_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='upload', verbose_name='头像'),
        ),
    ]
