# Generated by Django 2.2.4 on 2019-10-19 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_users_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='user_Token',
        ),
    ]
