# Generated by Django 2.2.4 on 2019-10-23 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0009_auto_20191020_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forecast',
            name='creator_id',
        ),
        migrations.RemoveField(
            model_name='forecast',
            name='isDel',
        ),
        migrations.RemoveField(
            model_name='forecast',
            name='update_id',
        ),
        migrations.AlterField(
            model_name='users',
            name='user_mail',
            field=models.CharField(default=1, max_length=20, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_phone',
            field=models.CharField(default=1, max_length=20, verbose_name='手机号码'),
        ),
    ]
