# Generated by Django 2.1.5 on 2019-10-30 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_auto_20191014_1910'),
        ('myApp', '0011_forecast_real_result'),
    ]

    operations = [
    ]
