# Generated by Django 2.1.5 on 2019-11-03 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0013_auto_20191101_2314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': '用户管理', 'verbose_name_plural': '用户管理'},
        ),
        migrations.RemoveField(
            model_name='users',
            name='user_id',
        ),
        migrations.AlterModelTable(
            name='users',
            table='myApp_users',
        ),
    ]
