# Generated by Django 2.1.5 on 2019-11-03 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0014_auto_20191103_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(default='12345678', editable=False, max_length=10000, verbose_name='登陆密码'),
        ),
    ]
