# Generated by Django 2.1.5 on 2019-11-03 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0015_auto_20191103_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='creator_id',
            field=models.IntegerField(default=1, verbose_name='创建者id'),
        ),
        migrations.AlterField(
            model_name='users',
            name='update_id',
            field=models.IntegerField(default=1, verbose_name='更新者id'),
        ),
    ]
